name: Run Automation Every 2 Days

on:
  schedule:
    - cron: '0 2 */2 * *'  # 2 AM UTC = 3 AM Portugal during DST
  workflow_dispatch:       # Optional manual trigger

jobs:
  run-bot-process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files in the root directory
      run: |
        echo "Current working directory: $(pwd)"
        echo "Listing files in current directory:"
        ls -alh

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the automation
      run: python auto_run.py  # This should be correct if file is in root
