name: Run Automation Every 2 Days

on:
  schedule:
    - cron: '0 2 */2 * *'  # 2 AM UTC = 3 AM Portugal during DST
  workflow_dispatch:       # Optional manual trigger

jobs:
  run-bot-process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the automation
      run: python auto_run.py
